// Week5/VueJs/vuejs-crash-course/vue-crash-course/src/components/Button.vue
<template>
    <button @click="onClick()" class="btn" :style="{ background: color }">{{ text }}</button>
</template>


<script>
export default {
    name: 'Button',
    props: {
        text: String,
        color: String
    },
    methods: {
        onClick() {
            console.log(this.text)
        }
    }
}
</script>

// Week7/react-crash-course/src/components/Button.jsx
import React from "react";
import PropTypes from "prop-types";

const Button = ({ color, text, onClick }) => {
  return (
    <button className="btn" onClick={onClick} style={{ background: color }}>
      {text}
    </button>
  );
};

Button.defaultProps = {
  color: "steelblue",
  text: "Add Task",
};

Button.propTypes = {
  color: PropTypes.string,
  text: PropTypes.string,
  onClick: PropTypes.func,
};

export default Button;
