// vuejs-options-vs-composition/src/components/Tasks.vue
<template>
    <div v-for="task of tasks" :key="task.id">
        <Task :task="task" @toggleReminder="$emit('toggleReminder', task.id)"
            @deleteTask="$emit('deleteTask', task.id)"></Task>
    </div>
</template>

<script>
import Task from './Task.vue';
export default {
    components: { Task },
    setup({ tasks }) {
    },
    props: {
        tasks: Array
    },
    emits: ['toggleReminder', 'deleteTask']
}
</script>

<style>
</style>

// Week7/react-crash-course/src/components/Tasks.jsx
import Task from "./Task";

const Tasks = ({ tasks, onDelete, toggleReminder }) => {
  return (
    <>
      {tasks.map((task) => {
        return (
          <Task
            key={task.id}
            task={task}
            onDelete={onDelete}
            toggleReminder={toggleReminder}
          />
        );
      })}
    </>
  );
};

export default Tasks;
